"""empty message

Revision ID: 047f840b61f1
Revises: 3b8c3cd248ce
Create Date: 2022-04-24 22:03:30.016585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047f840b61f1'
down_revision = '3b8c3cd248ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_interesse_usuario_projeto', sa.Column('fl_usuario_interesse', sa.Boolean(), nullable=True))
    op.add_column('tb_interesse_usuario_projeto', sa.Column('fl_projeto_interesse', sa.Boolean(), nullable=True))
    op.add_column('tb_interesse_usuario_projeto', sa.Column('fl_match', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_interesse_usuario_projeto', 'fl_match')
    op.drop_column('tb_interesse_usuario_projeto', 'fl_projeto_interesse')
    op.drop_column('tb_interesse_usuario_projeto', 'fl_usuario_interesse')
    # ### end Alembic commands ###
