"""empty message

Revision ID: bf3a2345276c
Revises: 258f7183a9fe
Create Date: 2021-11-27 23:52:49.578704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf3a2345276c'
down_revision = '258f7183a9fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_interesse_usuario_projeto',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('guid_usuario', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('id_projeto', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['id_projeto'], ['tb_projetos.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('guid'),
        sa.UniqueConstraint('guid_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_interesse_usuario_projeto')
    # ### end Alembic commands ###

