"""empty message

Revision ID: a5947ca03a14
Revises: bf3a2345276c
Create Date: 2021-11-28 00:37:25.246113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5947ca03a14'
down_revision = 'bf3a2345276c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tb_interesse_usuario_projeto_guid_usuario_key', 'tb_interesse_usuario_projeto', type_='unique')
    op.create_unique_constraint(None, 'tb_interesse_usuario_projeto', ['guid_usuario', 'id_projeto'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_interesse_usuario_projeto', type_='unique')
    op.create_unique_constraint('tb_interesse_usuario_projeto_guid_usuario_key', 'tb_interesse_usuario_projeto', ['guid_usuario'])
    # ### end Alembic commands ###
