"""empty message

Revision ID: 77475c9cb334
Revises: 4f154b560b09
Create Date: 2021-12-01 19:14:31.430813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77475c9cb334'
down_revision = '4f154b560b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_curso',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('nome_referencia', sa.String(), nullable=False),
    sa.Column('nome_exibicao', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('nome_exibicao'),
    sa.UniqueConstraint('nome_referencia')
    )
    op.create_table('tb_interesse',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('nome_referencia', sa.String(), nullable=False),
    sa.Column('nome_exibicao', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('nome_exibicao'),
    sa.UniqueConstraint('nome_referencia')
    )
    op.create_table('tb_rel_projeto_curso',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_projetos', sa.BigInteger(), nullable=True),
    sa.Column('id_cursos', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_cursos'], ['tb_curso.id'], ),
    sa.ForeignKeyConstraint(['id_projetos'], ['tb_projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_rel_projeto_interesse',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_projetos', sa.BigInteger(), nullable=True),
    sa.Column('id_cursos', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_cursos'], ['tb_interesse.id'], ),
    sa.ForeignKeyConstraint(['id_projetos'], ['tb_projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_rel_projeto_interesse')
    op.drop_table('tb_rel_projeto_curso')
    op.drop_table('tb_interesse')
    op.drop_table('tb_curso')
    # ### end Alembic commands ###
