"""empty message

Revision ID: 9bc1e0627292
Revises: 77475c9cb334
Create Date: 2021-12-01 22:38:20.121101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc1e0627292'
down_revision = '77475c9cb334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_rel_projeto_interesse', sa.Column('id_interesses', sa.BigInteger(), nullable=True))
    op.drop_constraint('tb_rel_projeto_interesse_id_cursos_fkey', 'tb_rel_projeto_interesse', type_='foreignkey')
    op.create_foreign_key(None, 'tb_rel_projeto_interesse', 'tb_interesse', ['id_interesses'], ['id'])
    op.drop_column('tb_rel_projeto_interesse', 'id_cursos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_rel_projeto_interesse', sa.Column('id_cursos', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tb_rel_projeto_interesse', type_='foreignkey')
    op.create_foreign_key('tb_rel_projeto_interesse_id_cursos_fkey', 'tb_rel_projeto_interesse', 'tb_interesse', ['id_cursos'], ['id'])
    op.drop_column('tb_rel_projeto_interesse', 'id_interesses')
    # ### end Alembic commands ###
