"""empty message

Revision ID: 3b8c3cd248ce
Revises: 9bc1e0627292
Create Date: 2021-12-02 09:10:41.376511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8c3cd248ce'
down_revision = '9bc1e0627292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_historico_projeto', sa.Column('url_imagem', sa.String(), nullable=True))
    op.add_column('tb_projetos', sa.Column('url_imagem', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_projetos', 'url_imagem')
    op.drop_column('tb_historico_projeto', 'url_imagem')
    # ### end Alembic commands ###
