"""empty message

Revision ID: b7bb1e2a5e5f
Revises: 43cd0ceaf5f2
Create Date: 2021-10-18 23:07:42.631793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7bb1e2a5e5f'
down_revision = '43cd0ceaf5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tb_projetos_descricao_key', 'tb_projetos', type_='unique')
    op.drop_constraint('tb_projetos_titulo_key', 'tb_projetos', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tb_projetos_titulo_key', 'tb_projetos', ['titulo'])
    op.create_unique_constraint('tb_projetos_descricao_key', 'tb_projetos', ['descricao'])
    # ### end Alembic commands ###
