"""empty message

Revision ID: 280e9621e69c
Revises: b7bb1e2a5e5f
Create Date: 2021-11-01 20:47:39.528646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '280e9621e69c'
down_revision = 'b7bb1e2a5e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_entidade_externa',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('tb_funcao_projeto',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tb_tipo_de_tag',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_historico_projeto',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_projetos', sa.BigInteger(), nullable=True),
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_projetos'], ['tb_projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('tb_historico_projeto_entidade',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_projetos', sa.BigInteger(), nullable=True),
    sa.Column('id_entidade', sa.BigInteger(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('mudanca', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_entidade'], ['tb_entidade_externa.id'], ),
    sa.ForeignKeyConstraint(['id_projetos'], ['tb_projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_historico_projeto_usuario',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_projetos', sa.BigInteger(), nullable=True),
    sa.Column('guid_user', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('mudanca', sa.String(), nullable=False),
    sa.Column('funcao', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_projetos'], ['tb_projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid_user')
    )
    op.create_table('tb_rel_projeto_entidade',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_projetos', sa.BigInteger(), nullable=True),
    sa.Column('id_entidade', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_entidade'], ['tb_entidade_externa.id'], ),
    sa.ForeignKeyConstraint(['id_projetos'], ['tb_projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_rel_projeto_user',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_projetos', sa.BigInteger(), nullable=True),
    sa.Column('id_funcao', sa.BigInteger(), nullable=True),
    sa.Column('guid_user', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['id_funcao'], ['tb_funcao_projeto.id'], ),
    sa.ForeignKeyConstraint(['id_projetos'], ['tb_projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid_user')
    )
    op.create_table('tb_tag',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('nome_de_referencia', sa.String(), nullable=False),
    sa.Column('id_tipo_de_tag', sa.BigInteger(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_de_tag'], ['tb_tipo_de_tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_historico_projeto_tag',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_projetos', sa.BigInteger(), nullable=True),
    sa.Column('id_tags', sa.BigInteger(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('mudanca', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_projetos'], ['tb_projetos.id'], ),
    sa.ForeignKeyConstraint(['id_tags'], ['tb_tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_relacao_projeto_tag',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_projetos', sa.BigInteger(), nullable=True),
    sa.Column('id_tags', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_projetos'], ['tb_projetos.id'], ),
    sa.ForeignKeyConstraint(['id_tags'], ['tb_tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_relacao_projeto_tag')
    op.drop_table('tb_historico_projeto_tag')
    op.drop_table('tb_tag')
    op.drop_table('tb_rel_projeto_user')
    op.drop_table('tb_rel_projeto_entidade')
    op.drop_table('tb_historico_projeto_usuario')
    op.drop_table('tb_historico_projeto_entidade')
    op.drop_table('tb_historico_projeto')
    op.drop_table('tb_tipo_de_tag')
    op.drop_table('tb_funcao_projeto')
    op.drop_table('tb_entidade_externa')
    # ### end Alembic commands ###
