"""empty message

Revision ID: ff7dd9dd6c22
Revises: 45673177344e
Create Date: 2021-11-03 20:02:05.866672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff7dd9dd6c22'
down_revision = '45673177344e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_tag', sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'tb_tag', ['guid'])
    op.add_column('tb_tipo_de_tag', sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'tb_tipo_de_tag', ['guid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_tipo_de_tag', type_='unique')
    op.drop_column('tb_tipo_de_tag', 'guid')
    op.drop_constraint(None, 'tb_tag', type_='unique')
    op.drop_column('tb_tag', 'guid')
    # ### end Alembic commands ###
