"""empty message

Revision ID: c00bae21a6e5
Revises: ff7dd9dd6c22
Create Date: 2021-11-23 21:59:27.438557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00bae21a6e5'
down_revision = 'ff7dd9dd6c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_historico_projeto_entidade', sa.Column('id_historico', sa.BigInteger(), nullable=True))
    op.drop_constraint('tb_historico_projeto_entidade_id_projetos_fkey', 'tb_historico_projeto_entidade', type_='foreignkey')
    op.create_foreign_key(None, 'tb_historico_projeto_entidade', 'tb_historico_projeto', ['id_historico'], ['id'])
    op.drop_column('tb_historico_projeto_entidade', 'id_projetos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_historico_projeto_entidade', sa.Column('id_projetos', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tb_historico_projeto_entidade', type_='foreignkey')
    op.create_foreign_key('tb_historico_projeto_entidade_id_projetos_fkey', 'tb_historico_projeto_entidade', 'tb_projetos', ['id_projetos'], ['id'])
    op.drop_column('tb_historico_projeto_entidade', 'id_historico')
    # ### end Alembic commands ###
